### ISSUE TITLE
Use log module instead of println

### ISSUE THREAD

**Issue by mikeconley** [amccreight/ipdl_parser#6]
There are a few places where we're println'ing, and something like [env_logger](https://doc.rust-lang.org/log/env_logger/) might be more appropriate - especially as we develop this thing, and might want to output debugging stuff.

Also, I figure this will be an easy place for me to get my feet wet writing Rust and contributing to this project.

**Comment by mikeconley** [comment]
(Willing to take this if you want to assign it)

**Comment by amccreight** [comment]
Sure. My only concern is about compile time for any new crates, if we're really going to put this on the hot path for Firefox compilation. But I suppose we can worry about that later if it is a problem.

**Comment by mikeconley** [comment]
Having talked it over with mccr8 in [this pull request](https://github.com/amccreight/ipdl_parser/pull/8), I think there are bigger fish to fry. I'm gonna close this one out for now.

**Comment by amccreight** [comment]
Thanks for looking into it.
