### ISSUE TITLE
Create some automated tests for the parser

### ISSUE THREAD

**Issue by mikeconley** [amccreight/ipdl_parser#9]
Goes without saying that we should probably make sure this thing is testable.

[Interestingly, the Python-based IPDL parser already has some test stuff](http://searchfox.org/mozilla-central/rev/82ebc0c5ea45477ef4a4bfb3bbff35069bd18cee/ipc/ipdl/test/ipdl/runtests.py), some of which we might be able to crib.

**Comment by amccreight** [comment]
Yeah, though most of those tests were broken for years and nobody noticed. Those tests are just "load this file without failing" or "load this file and fail" so we should really just use them wholesale here.

**Comment by amccreight** [comment]
My personal testing has just been "can you load every IPDL file from an m-c checkout". It would be nice to have some way to run that easily that is committed to the tree. I've just been using a hacky script to do it.

**Comment by amccreight** [comment]
Porting that runtests.py to Rust might be a decent starter project. Then set it up to run when you do cargo test or check. It'll require reorganizing the top level of the parser to be something you can invoke directly. Then somebody can just specify the existing ok and error directories from an existing mozilla-central checkout.

**Comment by amccreight** [comment]
Fixed.
